# A list of Warp Route token configs
# These configs will be merged with the warp routes in the configured registry
# The input here is typically the output of the Hyperlane CLI warp deploy command
---
tokens:
  - addressOrDenom: "0xc771f18cD1D625c34309B85708F72B00807b3F47"
    chainName: makachain
    connections:
      - token: ethereum|sepolia|0x3a34696fcb185a871B05549fd0B906C421C0e257
    decimals: 6
    name: USDC
    standard: EvmHypSynthetic
    symbol: USDC
  - addressOrDenom: "0x3a34696fcb185a871B05549fd0B906C421C0e257"
    chainName: sepolia
    collateralAddressOrDenom: "0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238"
    connections:
      - token: ethereum|makachain|0xc771f18cD1D625c34309B85708F72B00807b3F47
    decimals: 6
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
options: {}
