# A list of Warp Route token configs
# These configs will be merged with the warp routes in the configured registry
# The input here is typically the output of the Hyperlane CLI warp deploy command
---
tokens:
      - addressOrDenom: "0xff379444326821eafaad6B162A4033b4294Fe622"
        chainName: cogitusdemonetwork
        connections:
          - token: ethereum|sepolia|0x63EE69A022cb1D6EF9AE14600F3Ea827019B9707
        decimals: 6
        name: USDC
        standard: EvmHypSynthetic
        symbol: USDC
      - addressOrDenom: "0x63EE69A022cb1D6EF9AE14600F3Ea827019B9707"
        chainName: sepolia
        collateralAddressOrDenom: "0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238"
        connections:
          - token: ethereum|cogitusdemonetwork|0xff379444326821eafaad6B162A4033b4294Fe622
        decimals: 6
        name: USDC
        standard: EvmHypCollateral
        symbol: USDC
options: {}
