# A list of Warp Route token configs
# These configs will be merged with the warp routes in the configured registry
# The input here is typically the output of the Hyperlane CLI warp deploy command
---
tokens:
  - addressOrDenom: "0x94E67e741154393B129FE1cfc48213400F0F6062"
    chainName: pandasea
    connections:
      - token: ethereum|sepolia|0xaac87C27efEeD14325a9795aAd82BCF3A254dc49
    decimals: 6
    name: USDC
    standard: EvmHypSynthetic
    symbol: USDC
  - addressOrDenom: "0xaac87C27efEeD14325a9795aAd82BCF3A254dc49"
    chainName: sepolia
    collateralAddressOrDenom: "0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238"
    connections:
      - token: ethereum|pandasea|0x94E67e741154393B129FE1cfc48213400F0F6062
    decimals: 6
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
options: {}
